# ~/.tmuxinator/nixos-configuration.yml

name: nixos-configuration
root: /etc/nixos

windows:
  - configuration:
      layout: main-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - sudo vim configuration.nix
        - '# sudo nixos-rebuild switch'
